version: '3.7'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  hackathon-api:
    container_name: hackathon-backend
    image: ghcr.io/jenszech/hackathon-backend:develop
    environment:
      - NODE_ENV=develop
    volumes:
      - ./backend/volumes/config:/usr/src/app/volumes/config
      - ./backend/volumes/data:/usr/src/app/volumes/data
      - ./backend/volumes/database:/usr/src/app/volumes/database
    working_dir: /usr/src/app
    ports:
      - "3005:3005"

  hackathon-frontend:
    environment:
      - NODE_ENV=develop
    container_name: hackathon-frontend
    image: ghcr.io/jenszech/hackathon-frontend:develop
    ports:
    - "80:80"
    volumes:
      - ./frontend/volumes/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - hackathon-api
      