version: '3.7'
services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8081:8080

  hackathon-api:
    container_name: hackathon-backend
    image: ghcr.io/jenszech/hackathon-backend:develop
    environment:
      - NODE_ENV=develop
    volumes:
      - ./backend/volumes/config:/usr/src/app/volumes/config
      - ./backend/volumes/database:/usr/src/app/volumes/database
    working_dir: /usr/src/app
    networks:
      - web
      - internal
    ports:
      - "3005:3005"
    depends_on:
      - mysql

  hackathon-frontend:
    environment:
      - NODE_ENV=develop
    container_name: hackathon-frontend
    image: ghcr.io/jenszech/hackathon-frontend:develop
    ports:
    - "80:80"
    volumes:
      - ./frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
      - internal
    depends_on:
      - hackathon-api

  mysql:
    image: mysql:8.0
    container_name: hackathon-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: hackathon
      MYSQL_USER: hackathonuser
      MYSQL_PASSWORD: secretpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal

volumes:
  mysql-data:

networks:
  web:
  internal:
    driver: bridge
